### ISSUE TITLE
Downgrading

### ISSUE THREAD

**Issue by BasicVariable** [Embedded77/ETB#13]
When downgrading is set to "true" and upgrading is set to "false" the bot still queues upgrade trades.
EX: 
![image](https://user-images.githubusercontent.com/84644341/121380982-55719200-c913-11eb-827b-14696ea093a2.png)

*This especially happens when the config allows more the one item to be traded*

**Comment by Embedded77** [comment]
As I have again said multiple times, it will refuse to get more items if your inventory is too large. In this case, it was upgrading into yge
