### ISSUE TITLE
TradeForRap/TradeForValue

### ISSUE THREAD

**Issue by emilyxox** [Embedded77/ETB#17]
TradeForRap = false
TradeForValue = true

Basically controls if the bot sends for rap, value, or both.

i don't want my bot sending for rap items (because of the rare occasion where itll trade for a proj that i havent seen yet) so this'd help

**Comment by Embedded77** [comment]
Just flag every rap item as donotget, theres a list in the repository

**Comment by Embedded77** [comment]
It'll also automark projecteds, so /shrug

**Comment by emilyxox** [comment]
it didn't automark the lucky shade things, and adding every rap item makes my config huge, itd be nicer as a config setting but.
