### ISSUE TITLE
Blocklist

### ISSUE THREAD

**Issue by Sinful-9149** [Embedded77/ETB#19]
A table that you can add users to not send trades to, that way you can easily avoid sending to other trade bots. I can't count the number of times I've seen embedded users in both my inbounds and outbounds.

**Comment by Embedded77** [comment]
just manually block on roblox

**Comment by Sinful-9149** [comment]
problem is im friends with some other trade botters so I cant exactly block them.. and roblox has a limit to how many users you can block as well

**Comment by Sinful-9149** [comment]
theres also updated lists of uuc userids that olympian users use for inbound accepting which have like 100+ ids
