### ISSUE TITLE
Problem with the command $mass_send

### ISSUE THREAD

**Issue by Negative-tech** [Embedded77/ETB#2]
### This is still happening in the latest **ETB** update.

When you use the `$mass_send` command without anything else the bot crashes and stops working.

It also happens if you use the same command in the wrong way.

Image of the error: https://cdn.discordapp.com/attachments/826572028064170026/838823803206893608/unknown.png

Possible solution:
When the user uses the **$mass_send** command incorrectly, the bot will send a message like this.

`This is not correct, it has to be like this! $mass_send 123 [123,1234,12345,1234567]`

**Comment by Embedded77** [comment]
> ### This is still happening in the latest **ETB** update.
> When you use the `$mass_send` command without anything else the bot crashes and stops working.
> 
> It also happens if you use the same command in the wrong way.
> 
> Image of the error: https://cdn.discordapp.com/attachments/826572028064170026/838823803206893608/unknown.png
> 
> Possible solution:
> When the user uses the **$mass_send** command incorrectly, the bot will send a message like this.
> 
> `This is not correct, it has to be like this! $mass_send 123 [123,1234,12345,1234567]`

Good idea.

**Comment by Embedded77** [comment]
Fixed for 3.3.6
