### ISSUE TITLE
Use rbx.flip history to find trade combinations 

### ISSUE THREAD

**Issue by BasicVariable** [Embedded77/ETB#26]
Flippers tend to lowball their recently flipped items so it would be nice if the Autoplugger scanned Rbx.flip history for trade combinations.

**Comment by zMisfortune** [comment]
> Flippers tend to lowball their recently flipped items so it would be nice if the Autoplugger scanned Rbx.flip history for trade combinations.

yes plz flippers are retarded they give like yum for 10k op with iv and shit ez

**Comment by Embedded77** [comment]
Done
