### ISSUE TITLE
Mass_Send for Downgrading

### ISSUE THREAD

**Issue by HappyTappy** [Embedded77/ETB#33]
I was thinking you make a command like $dMass itemid [uaid] and the bot will find all the premium owners with that item and find trade combos with those users that include the itemid you want and send 3v1, 3v2, 4v2, etc whatever it finds first that fits your ratios

**Comment by Embedded77** [comment]
![image](https://user-images.githubusercontent.com/59213351/123343737-56fca600-d520-11eb-80de-4598ea8696b8.png)
